# Generated by Django 5.1 on 2025-03-03 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('passw', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('gender', models.CharField(blank=True, choices=[('male', 'MALE'), ('female', 'FEMALE'), ('others', 'OTHERS')], max_length=10, null=True)),
                ('category', models.CharField(choices=[('organizers and facilitators', 'ORGANIZERS AND FACILITATORS'), ('mentors and experts', 'MENTORS AND EXPERTS'), ('sponsors or donors', 'SPONSORS AND DONORS'), ('creators and sharers', 'CREATORS AND SHARERS')], max_length=30)),
                ('approval_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('passw', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('gender', models.CharField(blank=True, choices=[('male', 'MALE'), ('female', 'FEMALE'), ('others', 'OTHERS')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('not received', 'NOT RECIEVED'), ('in progress', ' IN PROGRESS'), ('completed', 'COMPLETED')], default='not received', max_length=20)),
                ('mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='com.mod')),
            ],
        ),
    ]
