# Generated by Django 5.1 on 2025-03-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0005_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg',
            name='location',
            field=models.CharField(default='India', max_length=50),
        ),
    ]
