# Generated by Django 5.1 on 2025-03-12 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0006_reg_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg',
            name='bloodgroup',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True),
        ),
    ]
