# Generated by Django 5.1 on 2025-03-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0008_mentoringsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
