# Generated by Django 5.1 on 2025-03-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0009_mod_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
