# Generated by Django 5.1 on 2025-03-22 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0011_mod_bloodgroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mod',
            old_name='selected',
            new_name='is_selected',
        ),
    ]
