# Generated by Django 5.1 on 2025-03-22 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0012_rename_selected_mod_is_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mod',
            name='is_rejected',
        ),
        migrations.RemoveField(
            model_name='mod',
            name='is_selected',
        ),
        migrations.CreateModel(
            name='VolunteerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_selected', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('admin_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='com.adminrequest')),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='com.mod')),
            ],
            options={
                'unique_together': {('admin_request', 'moderator')},
            },
        ),
    ]
