# Generated by Django 5.1 on 2025-03-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0014_mod_is_rejected_mod_is_selected_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mod',
            name='is_rejected',
        ),
        migrations.RemoveField(
            model_name='mod',
            name='is_selected',
        ),
        migrations.AddField(
            model_name='mod',
            name='rejected_requests',
            field=models.ManyToManyField(blank=True, related_name='rejected_volunteers', to='com.adminrequest'),
        ),
        migrations.AddField(
            model_name='mod',
            name='selected_requests',
            field=models.ManyToManyField(blank=True, related_name='selected_volunteers', to='com.adminrequest'),
        ),
    ]
