# Generated by Django 5.1 on 2025-03-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0015_remove_mod_is_rejected_remove_mod_is_selected_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mod',
            name='rejected_requests',
        ),
        migrations.RemoveField(
            model_name='mod',
            name='selected_requests',
        ),
        migrations.AddField(
            model_name='mod',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mod',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
