# Generated by Django 5.1.7 on 2025-03-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0017_chatmessage_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminrequest',
            name='approved_volunteers',
            field=models.ManyToManyField(blank=True, related_name='approved_camps', to='com.mod'),
        ),
    ]
