# Generated by Django 5.1.7 on 2025-03-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0019_chatmessage_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='bloodgroup',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
