# Generated by Django 5.1.7 on 2025-03-28 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0022_alter_session_by_mentor_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='com.session_by_mentor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='com.reg')),
            ],
            options={
                'unique_together': {('session', 'user')},
            },
        ),
    ]
