# Generated by Django 5.1.7 on 2025-03-28 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0023_sessionregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='requested', max_length=20)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='com.session_by_mentor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='com.reg')),
            ],
        ),
        migrations.AddField(
            model_name='session_by_mentor',
            name='participants',
            field=models.ManyToManyField(related_name='joined_sessions', through='com.SessionParticipation', to='com.reg'),
        ),
    ]
