# Generated by Django 5.1.7 on 2025-03-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0024_sessionparticipation_session_by_mentor_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='session_by_mentor',
            name='session_type',
            field=models.CharField(blank=True, default='None', max_length=50),
        ),
    ]
