# Generated by Django 5.1.7 on 2025-04-08 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0025_session_by_mentor_session_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreativeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('article', 'Article'), ('paper', 'Research Paper'), ('book', 'Book'), ('thought', 'Thought'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(help_text='Brief description or context')),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='creative/files/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or external video link', null=True)),
                ('thoughts', models.TextField(blank=True, help_text='Write something positive or motivational', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='com.mod')),
            ],
        ),
    ]
