# Generated by Django 5.1.7 on 2025-04-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0026_creativecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='creativecontent',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
