# Generated by Django 5.1.7 on 2025-04-12 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0027_creativecontent_like_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='com.creativecontent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='com.reg')),
            ],
            options={
                'unique_together': {('user', 'content')},
            },
        ),
    ]
