# Generated by Django 5.1.7 on 2025-04-12 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0028_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='com.creativecontent'),
        ),
    ]
