# Generated by Django 5.1.7 on 2025-04-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0029_alter_like_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_by_mentor',
            name='location',
            field=models.URLField(blank=True, help_text='Zoom or meet links', null=True),
        ),
    ]
