# Generated by Django 5.1.7 on 2025-04-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0030_alter_session_by_mentor_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentorfeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=50)),
                ('rating', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='mod',
            name='category',
            field=models.CharField(choices=[('mentors and experts', 'MENTORS AND EXPERTS'), ('sponsors or donors', 'SPONSORS AND DONORS'), ('creators and sharers', 'CREATORS AND SHARERS')], max_length=30),
        ),
    ]
