# Generated by Django 5.1.7 on 2025-04-19 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0031_mentorfeedback_alter_mod_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=50)),
                ('rating', models.IntegerField(max_length=5)),
                ('mod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='com.mod')),
                ('usser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='com.reg')),
            ],
        ),
        migrations.DeleteModel(
            name='Mentorfeedback',
        ),
    ]
