# Generated by Django 5.1.7 on 2025-04-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0032_feedback_delete_mentorfeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='mod',
        ),
        migrations.AddField(
            model_name='feedback',
            name='choice',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
