# Generated by Django 5.1.7 on 2025-04-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0033_remove_feedback_mod_feedback_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
